require 'voxpupuli/test/rake'
require 'voxpupuli/acceptance/rake'
require 'voxpupuli/release/rake_tasks'
require 'ra10ke'
require 'onceover/rake_tasks'

Ra10ke::RakeTask.new

# disable ghostbuster globally
puppet_lint_disable_checks = %w[
  ghostbuster_classes
  ghostbuster_defines
  ghostbuster_facts
  ghostbuster_files
  ghostbuster_functions
  ghostbuster_hiera_files
  ghostbuster_templates
  ghostbuster_types
]

puppet_lint_disable_checks.each do |check|
  PuppetLint.configuration.send(:"disable_#{check}")
end

namespace :voxpupuli do
  namespace :custom do
    desc 'Lint with all puppet-lint checks'
    task :lint_all do
      # re-enable by puppetlabs disabled checks from puppetlabs/spec_helper
      # see: https://github.com/puppetlabs/puppetlabs_spec_helper/blob/70de49db0a242f83e9ff39ea8a03c830339f8368/lib/puppetlabs_spec_helper/rake_tasks.rb#L169-L177
      puppet_lint_enable_checks = %w[
        140chars
        class_inherits_from_params_class
        class_parameter_defaults
        autoloader_layout
        documentation
        single_quote_string_with_variables
      ]

      puppet_lint_enable_checks.each do |check|
        PuppetLint.configuration.send(:"enable_#{check}")
      end

      Rake::Task[:lint].invoke
    end

    desc 'Who you gonna call? Ghostbusters!'
    task :ghostbuster do
      # enable ghostbuster
      puppet_lint_enable_checks = %w[
        ghostbuster_classes
        ghostbuster_defines
        ghostbuster_facts
        ghostbuster_files
        ghostbuster_functions
        ghostbuster_hiera_files
        ghostbuster_templates
        ghostbuster_types
      ]

      puppet_lint_enable_checks.each do |check|
        PuppetLint.configuration.send(:"enable_#{check}")
      end
    end
  end
end
